waitUntil {!(isNull player)};
waitUntil {player==player};
switch (side player) do
{
case WEST:
{
player createDiaryRecord ["Diary",["Version 1.1","Changes for 1.1<br/><br/>1. Modified offroad trigger to fire immediately instead of waiting 3 seconds. Players may encounter messages that seem erroneous when Food Truck is driving on bridges.<br/><br/>2. removed 'foreach' in initplayerlocal, so all gear (including radios) don't keep being reapplied whenever someone joins server.<br/><br/>3. Updated briefing to include Friendly information such as vehicle capacity, spare parts, night mission box.<br/><br/>4. Tweaked inventory cargo of vehicles.<br/><br/>5. Removed ACE spector, enabled ARMA 3 spectator.<br/><br/>6. Provided role description for each unit in player slot screen, and then updated init with setGroupID to sync it- so there is less confusion as far as who is in what group.<br/><br/>7. Some grammar clean up, if you ignore the previous paragraphs.<br/><br/>8. Updated OnLoad screens so they are less redundant with mission name.<br/><br/>9. Added GPS to Squad Leaders and Sniper now has Laser Rangefinder.<br/><br/>10. Adjusted mine placements and numbers<br/><br/>11. Removed information from Notes and added to Enemy Intel, added more information to Enemy Intel.<br/><br/>12. Removed epinephrine from opfor, since the civilian kill script should be obvious enough if you killed a bad guy or not.<br/><br/><br/>Version 1:<br/>This is the first release version of the ACE rebuild. I created this mission originally for ARMA 2, and then ported it to work with ARMA 3 and the AGM modset years ago. Many 'manual' things like bomb scripts and waypoints have been removed in favor of some scripted automation and things like BIS's patrol."]];
player createDiaryRecord ["Diary",["Notes","This mission has had a lot of randomization added. In the first release version, there is a 20% chance of each 'event' occurring. An 'event' is each instance of an assault squad, ambush, IED barrel, Mines, suicide bombers, etc. Even in the situations of an assault squad spawning, the entire squad may not spawn. So, while it is highly unlikely that everything will happen, a number of things probably will.<br/><br/>The uniforms of both civilians and certain separatists are randomized, but from the same set of possible outfit combinations, so there should not be any indication something is wrong until something goes wrong."]];
player createDiaryRecord ["Diary",["Friendly Intel", "<br/><br/>Transport and Seats:<br/><br/><font color='#edce47'>HEMTT Transport (Food Truck)</font><br/>    1 Driver<br/>    2 Rear Gunners<br/>    15 Passengers<br/><br/><font color='#edce47'>M113A3 (M240)</font><br/>    1 Driver<br/>    1 Turret Gunner<br/>    2 Hatch Gunners<br/>    9 passengers<br/><br/><font color='#edce47'>RG-33</font><br/>    1 Driver<br/>    7 Passengers<br/><br/>Gear:<br/>Extra gear is stowed in the inventory of each vehicle. The Food Truck does not have weapons, but has spare medical supplies. The M113A3 has extra Javelin missiles.<br/><br/>A crate with night mission supplies and extra radios is near the containers.<br/><br/>Spare wheels and Tracks are also available near the cargo containers."]];
player createDiaryRecord ["Diary",["Enemy Intel","Based on previous dealings with the separatists, here are the possible tactics they will employ:<br/><br/><font color='#edce47'>1. Small squad assaults</font><br/>Squads of up to 7 lightly armed fighters with various unit type compositions, some may be carrying RPGs<br/><br/><font color='#edce47'>2. Lone gunners</font><br/>Some snipers or RPG gunners may be hiding out in key areas, including buildings in towns<br/><br/><font color='#edce47'>3. AT Mines</font><br/><img image='media\amine.jpg' width='128' height='128'/><br/>Watch out for placed mines in the road along our route. They are likely to be in places that are hard to see. They may also be near other features.<br/><br/><font color='#edce47'>4. IEDs</font><br/><img image='media\iedbarrel.jpg' width='128' height='128'/><br/>These barrels may be hidden along our route and are set to explode if the Food Truck gets close enough. They are likely to be slightly hidden along our route and near key areas. Explosive Specialists can defuse them.<br/><br/><font color='#edce47'>5. Static Guns</font><br/> We know the separatists have some static weaponry at their disposal and are likely to employ them. Many will likely set up at a distance with good viewing angles.<br/><br/><font color='#edce47'>6. Suicide Bombers</font><br/>Separatists dressed as civilians with a bomb strapped to their chest may try to run to the truck and detonate themselves.<br/><br/><font color='#edce47'>7. Time Bombs</font><br/>Separatists dressed as civilians may try to place explosives near the Food Truck<br/><br/><font color='#edce47'>8. Anarchists</font><br/><img image='media\anarch.jpg' width='128' height='128'/><br/>Separatists dressed as civilians have been known to run near a crowded area and throw grenades.<br/><br/><font color='#edce47'>9. Technicals</font><br/>Two man teams may try to assault with a truck mounted .50 cal.<br/><br/><font color='#edce47'>10. Car Bombs</font><br/>Separatists dressed as civilians may try to destroy the Food Truck by detonating their cars when they get near.<br/><br/><font color='#edce47'>11. Ambush</font><br/> In addition to Separatist regulars who may be patrolling in key areas along our route, some small unit compositions may be dressed as civilians with hidden weapons waiting for the perfect time to strike."]];
player createDiaryRecord ["Diary",["Mission","Protect the <font color='#edce47'><marker name='portmark'>Food Truck</marker></font> while it makes deliveries to these three towns on the island: <font color='#edce47'><marker name='dormark'>Dorida</marker></font>, <font color='#edce47'><marker name='chamark'>Chalkeia</marker></font>, and <font color='#edce47'><marker name='panmark'>Panagia</marker></font>.<br/><br/>The Food Truck must stay in the delivery area for 3 minutes in order to give citizens ample time to collect food, where they will pick up backpacks from the truck. You will be notified when the Food Truck is within the boundaries and when it has completed its delivery to the town. Generally, the objective marker in each town is the approximate center for the delivery area.<br/><br/>The Food Truck must stay on the roads and not be totally destroyed or else the mission will fail.<br/><br/>Once the Food Truck has completed delivery to each town, it must continue to the end point at <font color='#edce47'><marker name='airmark'>Selokano Airfield</marker></font>.<br/><br/>While the Food Truck and the rest of us are the primary targets, too many civilian deaths will cause the citizens of the island to lose confidence in our ability to control the peace."]];
player createDiaryRecord ["Diary",["Overview","The recent civil war has led to widespread food shortages across the island. While things have somewhat stabilized, there is still a sizeable contingent of separatists.<br/><br/>In order for the fragile peace to hold, we need to deliver food to key towns along the island.<br/><br/>A well-fed populace would weaken support for the separatists, so expect an attack."]];
};
case EAST:
{


};
case RESISTANCE:
{


};
case CIVILIAN:
{


};
};